### PR TITLE
Update pmml notebook

### PR DESCRIPTION
**Pull request by rnostream**
- changed the sample file handling to "download from GitHub and drag'n'drop by hand"
- changed the code to use no SPL operators
- changed the descriptions to be more descriptive

### CODE REVIEW

**Comment by natashadsilva** [comment]
Hi Ronald,
After reviewing the notebook I have the following comments:

1. The blue box in step 2.2 that highlights on what  someone needs to know in order to score PMML models using the toolkit is excellent!  This is a great way to present key information.
2. Overall,  this notebook is meant to be a template to _show the basic pattern_ of what to do to score PMML models in real time.  Keeping that in mind,  I found there was a lot of extra detail/comments that prevents the main point from being clear.
3. The key steps (load model, preprocess etc) should form the skeleton of the notebook, and should be listed in the table of contents. Each step should be its own subheading.
Right now the notebook table of contents is very generic and the key things that need to be done are not emphasized.
4. The other part that has the potential to be confusing is having to change tuple formats.  Most have never heard of `StreamsSchema` so it needs some explanation. They have to do 2 conversions 1) convert incoming stream to Streams structured schema. 2) map model features to attributes in the incoming data.
For example, something like this is needed:

> “Our incoming data is a stream of `dicts` of the following format:
>  `{'age': 36, 'sex': 'F', .. }`
> We are going to change it to a [structured schema](https://streamsxtopology.readthedocs.io/en/stable/streamsx.topology.schema.html#streamsx.topology.schema.StreamSchema) that Streams supports  using `map`, …with this code: ….
> You can define your own schema for your own data by consulting this doc..”
List reference information for me to create mappings for my own data types.
5. Instead of explaining the background for certain parts, just add relevant links where they can go to learn more if needed.

Thank you!

**Comment by ddebrunner** [comment]
The notebook formatting seems messed up after `2.1 Define Data Input` in both the GitHub viewer and the online notebook viewer: https://nbviewer.jupyter.org/github/IBMStreams/sample.starter_notebooks/blob/6b138e713dcfcb684c5636e3ea7de6ca652cc1bb/Streams-PMMLScoringSample.ipynb

**Comment by ddebrunner** [comment]
The structured schema needs to be defined using a typed named tuple if it isn't already.

**Comment by natashadsilva** [comment]
@ddebrunner the notebook looks ok in Jupyter. 
I think we should hold off on using named tuples for now if they aren't supported in 3.5.

**Comment by ddebrunner** [comment]
@natashadsilva ICP4D is Python 3.6 and we want to make natural for Python developers using it.

**Comment by ddebrunner** [comment]
@natashadsilva @rnostream @petenicholls 

FYI - I installed ReviewNB on this repo which does side by side diffs of notebooks.

Try: https://app.reviewnb.com/IBMStreams/sample.starter_notebooks/pull/5/files/

**Comment by rnostream** [comment]
@ddebrunner ReviewNB is great, but I don't see the the IBMstreams repos only my own. Having the correct link show it. Seems to be little bug. Any way it's great. 
Developing the the NB locally and in ICP show correct formatting, so it's just a GitHub issue. But I don't want to miss the features Jupyter give ... only because GitHub doesn't show well.

**Comment by natashadsilva** [comment]
@rnostream is this the latest version of the notebook?

**Comment by rnostream** [comment]
@natashadsilva No, this pull request can be closed. Your last commit contains contains already a newer version.

**Pull request closed without merging**
