### PR TITLE
Add a new Notebook template for connecting Streams with a bare Kafka broker

### PR DESCRIPTION
**Pull request by RolefH**
This template is more than the basic publish-subscribe. It shows:
- How to create a Kafka consumer group with Python topology
- How to use structured schemas
- How to parellelize processing based on a hash

### CODE REVIEW

**Comment by ddebrunner** [comment]
Section 2.2
Why is the function called `flat_message_json`?
It's converting a JSON message to a SensorMessage, not flattening anything.
Is it really a `SensorMessage` or a `SensorReading` or `SensorEvent`?

**Comment by RolefH** [comment]
> Section 2.4
> 
> _you would use a sink function (similar to the source function) and invoke it using Stream.for_each._
> 
> How is a sink function similar to a source function?

A source function is of course not similar to a sink function, but the way how source and sink functions are used, is similar. A source function is used as an argument to `Topology.source(func, name)`, a sink function is an argument to `Stream.for_each(func, name)`.

Removed the _(similar to the source function)_ as the similarity is really only the fact that the function is used as an argument to a function call.

> 
> Is an explanation needed for why the Streams publish is after the end_parallel? Typically it would be in the parallel region.

I wanted to show a flow from a parallelized source over a parallelized processing, the end of the parallel region up to a termination. A view after the `end_parallel` cannot be seen as a termination as it samples the stream and potentially loses tuples.
That's why I placed the `publish` after the `end_parallel`. Many sinks can be placed in the parallel region, many sinks should not be placed in the parallel region, for example those, which have a big resource consumption like the COS sink.

**Comment by RolefH** [comment]
> Section 2.2
> Why is the function called `flat_message_json`?
> It's converting a JSON message to a SensorMessage, not flattening anything.
> Is it really a `SensorMessage` or a `SensorReading` or `SensorEvent`?
> 
> `negativ` missing an `e`

I really puzzled my head over how to name the function. What is the function doing? It parses JSON and assigns attributes to a new tuple. So I renamed it to `parse_json_to_tuple`, and the resulting stream from `receivedParallelPartitionedFlattened` to `receivedParallelPartitionedParsed`.

**Comment by RolefH** [comment]
PR is obsolete.

**Pull request closed without merging**
